apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.postgres.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "deploy-history.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.postgres.name }}
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: {{ .Values.postgres.name }}
  ports:
    - name: postgres
      port: {{ .Values.postgres.service.port }}
      targetPort: postgres
